CREATE TABLE users (
  id int NOT NULL AUTO_INCREMENT,
  email varchar(200) NOT NULL,
  password varchar(200) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY id_UNIQUE (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ;

CREATE TABLE weight (
  id int NOT NULL AUTO_INCREMENT,
  user_id int NOT NULL,
  data DATE NOT NULL,
  value FLOAT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY id_UNIQUE (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ;

